apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: operators
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: kj853069/ultimate-cicd:59
        ports:
        - containerPort: 8080
